//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingCard
    {
        public AccountingCard()
        {
            this.AssetComponents = new HashSet<AssetComponent>();
            this.AssetMovements = new HashSet<AssetMovement>();
        }
    
        public int CardID { get; set; }
        public int ModelID { get; set; }
        public string AssetName { get; set; }
        public string InventoryNumber { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public Nullable<System.DateTime> DecommissionDate { get; set; }
        public string DecommissionDocName { get; set; }
        public string DecommissionDocNumber { get; set; }
        public Nullable<System.DateTime> DecommissionDocDate { get; set; }
        public string PreciousMetals { get; set; }
        public Nullable<decimal> InitialCost { get; set; }
        public int ConditionID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public int ResponsibleEmployeeID { get; set; }
        public Nullable<int> CurrentHolderID { get; set; }
        public string Notes { get; set; }
    
        public virtual AssetCondition AssetCondition { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual AssetModel AssetModel { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<AssetComponent> AssetComponents { get; set; }
        public virtual ICollection<AssetMovement> AssetMovements { get; set; }
    }
}
