//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetModel
    {
        public AssetModel()
        {
            this.AccountingCards = new HashSet<AccountingCard>();
        }
    
        public int ModelID { get; set; }
        public int AssetTypeID { get; set; }
        public string Brand { get; set; }
        public string ModelName { get; set; }
    
        public virtual ICollection<AccountingCard> AccountingCards { get; set; }
        public virtual AssetType AssetType { get; set; }
    }
}
