//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetComponent
    {
        public int ComponentID { get; set; }
        public int CardID { get; set; }
        public string ComponentName { get; set; }
        public string ComponentNumber { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
    
        public virtual AccountingCard AccountingCard { get; set; }
    }
}
