//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetType
    {
        public AssetType()
        {
            this.AssetModels = new HashSet<AssetModel>();
        }
    
        public int AssetTypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<AssetModel> AssetModels { get; set; }
    }
}
