//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCondition
    {
        public AssetCondition()
        {
            this.AccountingCards = new HashSet<AccountingCard>();
            this.AssetMovements = new HashSet<AssetMovement>();
        }
    
        public int ConditionID { get; set; }
        public string ConditionName { get; set; }
    
        public virtual ICollection<AccountingCard> AccountingCards { get; set; }
        public virtual ICollection<AssetMovement> AssetMovements { get; set; }
    }
}
