//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetMovement
    {
        public int MovementID { get; set; }
        public int CardID { get; set; }
        public int SequenceNumber { get; set; }
        public System.DateTime MovementDate { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public int HolderEmployeeID { get; set; }
        public Nullable<int> TransferredByID { get; set; }
        public int ConditionID { get; set; }
        public string Notes { get; set; }
    
        public virtual AccountingCard AccountingCard { get; set; }
        public virtual AssetCondition AssetCondition { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Room Room { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
