//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.AccountingCards = new HashSet<AccountingCard>();
            this.AssetMovements = new HashSet<AssetMovement>();
            this.Department1 = new HashSet<Department>();
            this.EmployeePositions = new HashSet<EmployeePosition>();
            this.Rooms = new HashSet<Room>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<AccountingCard> AccountingCards { get; set; }
        public virtual ICollection<AssetMovement> AssetMovements { get; set; }
        public virtual ICollection<Department> Department1 { get; set; }
        public virtual Department Department2 { get; set; }
        public virtual ICollection<EmployeePosition> EmployeePositions { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
