//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.AccountingCards = new HashSet<AccountingCard>();
            this.AccountingCards1 = new HashSet<AccountingCard>();
            this.AssetMovements = new HashSet<AssetMovement>();
            this.AssetMovements1 = new HashSet<AssetMovement>();
            this.EmployeePositions = new HashSet<EmployeePosition>();
        }
    
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string SNILS { get; set; }
        public string INN { get; set; }
        public Nullable<int> PassportID { get; set; }
        public string PhoneMobile { get; set; }
        public string PhoneWork { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> DismissDate { get; set; }
    
        public virtual ICollection<AccountingCard> AccountingCards { get; set; }
        public virtual ICollection<AccountingCard> AccountingCards1 { get; set; }
        public virtual ICollection<AssetMovement> AssetMovements { get; set; }
        public virtual ICollection<AssetMovement> AssetMovements1 { get; set; }
        public virtual EmployeePassport EmployeePassport { get; set; }
        public virtual ICollection<EmployeePosition> EmployeePositions { get; set; }
    }
}
