//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePassport
    {
        public EmployeePassport()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int PassportID { get; set; }
        public string Series { get; set; }
        public string PassportNumber { get; set; }
        public string IssuedBy { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public string DivisionCode { get; set; }
        public string BirthPlace { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
