//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaterialAssetsEntities : DbContext
    {
        public MaterialAssetsEntities()
            : base("name=MaterialAssetsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountingCard> AccountingCards { get; set; }
        public DbSet<AssetComponent> AssetComponents { get; set; }
        public DbSet<AssetCondition> AssetConditions { get; set; }
        public DbSet<AssetModel> AssetModels { get; set; }
        public DbSet<AssetMovement> AssetMovements { get; set; }
        public DbSet<AssetType> AssetTypes { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeePassport> EmployeePassports { get; set; }
        public DbSet<EmployeePosition> EmployeePositions { get; set; }
        public DbSet<Position> Positions { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<vw_AssetCurrentLocation> vw_AssetCurrentLocation { get; set; }
    }
}
