//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.AccountingCards = new HashSet<AccountingCard>();
            this.AssetMovements = new HashSet<AssetMovement>();
            this.EmployeePositions = new HashSet<EmployeePosition>();
        }
    
        public int RoomID { get; set; }
        public int DepartmentID { get; set; }
        public string RoomNumber { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AccountingCard> AccountingCards { get; set; }
        public virtual ICollection<AssetMovement> AssetMovements { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<EmployeePosition> EmployeePositions { get; set; }
    }
}
