//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAssetsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AssetCurrentLocation
    {
        public int CardID { get; set; }
        public string InventoryNumber { get; set; }
        public string AssetName { get; set; }
        public string Brand { get; set; }
        public string ModelName { get; set; }
        public string AssetType { get; set; }
        public string CurrentDepartment { get; set; }
        public string CurrentRoom { get; set; }
        public string CurrentCondition { get; set; }
        public string ResponsiblePerson { get; set; }
        public string CurrentHolder { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public Nullable<System.DateTime> DecommissionDate { get; set; }
        public Nullable<decimal> InitialCost { get; set; }
        public int ModelID { get; set; }
        public int AssetTypeID { get; set; }
        public int ConditionID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public int ResponsibleEmployeeID { get; set; }
        public Nullable<int> CurrentHolderID { get; set; }
    }
}
